//
// Created by spak on 11/15/22.
//
#ifndef SPOOKY_ACTION_USER_SETTINGS_H
#define SPOOKY_ACTION_USER_SETTINGS_H

#include <sdkconfig.h>

#undef WOLFSSL_ESPIDF
#define WOLFSSL_ESPIDF
#define WOLFSSL_ESPWROOM32
#define BENCH_EMBEDDED
#define USE_CERT_BUFFERS_2048
//#define WOLFSSL_TLS13
#define HAVE_TLS_EXTENSIONS
#define WC_RSA_PSS
#define HAVE_HKDF
#define HAVE_AEAD
#define HAVE_SUPPORTED_CURVES
#define NO_FILESYSTEM
#define HAVE_AESGCM
#define WOLFSSL_SHA384
#define WOLFSSL_SHA512
#define HAVE_ECC
#define HAVE_CURVE25519
#define CURVE25519_SMALL
#define HAVE_ED25519
#define HAVE_ALPN
#define HAVE_SNI
#define NO_MAIN_DRIVER
//#define NO_DSA
//#define NO_DH
#define NO_MD4
//#define NO_DES3
#define NO_RC4
#define NO_RABBIT
#define NO_OLD_TLS
#define OPENSSL_EXTRA_X509_SMALL
#define WOLFSSL_ALT_CERT_CHAINS
#define WOLFSSL_BASE64_ENCODE
//#define WOLFSSL_STATIC_RSA
//#define WOLFSSL_STATIC_PSK
//#define WOLFSSL_STATIC_DH
#define OPENSSL_EXTRA
#define WOLFSSL_SMALL_CERT_VERIFY
#define WOLFSSL_SMALL_STACK
#define SMALL_SESSION_CACHE
//#define HAVE_PKCS7
#if defined(HAVE_PKCS7)
#define HAVE_AES_KEYWRAP
#define HAVE_X963_KDF
#define WOLFSSL_AES_DIRECT
#endif
//#define WOLFSSL_AES_DIRECT
//#define WOLFSSL_AES_COUNTER

#if defined(WOLFSSL_ESPWROOM32SE)
#define WOLFSSL_ATECC508A
#define HAVE_PK_CALLBACKS
//#define CUSTOM_SLOT_ALLOCATION
#endif

#if defined(WOLFSSL_ESPWROOM32) || defined(WOLFSSL_ESPWROOM32SE)
#define ESP32_USE_RSA_PRIMITIVE
#define EPS_RSA_EXPT_XBTIS 36
#define ESP_RSA_MULM_BITS 2000
#endif

//#define DEBUG_WOLFSSL
//#define WOLFSSL_ESP32WROOM32_CRYPT_DEBUG
//#define WOLFSSL_ATECC_DEBUG
#define NO_ASN_TIME
#define XTIME time
#define XGMTIME(c, t) gmtime((c))
#if !defined(CONFIG_IDF_TARGET_ESP32)
#define NO_ESP32WROOM32_CRYPT
#endif
#define NO_WOLFSSL_ESP32WROOM32_CRYPT_HASH
//#define NO_WOLFSSL_ESP32WROOM32_CRYPT_AES */
//#define NO_WOLFSSL_ESP32WROOM32_CRYPT_RSA_PRI */
#define ESP_RSA_TIMEOUT_CNT 0x249F00

#endif